import type { ChatMessage, ChatThread } from '@/types/clinical';

export function buildThreadId(patientId: string, specialistUserId: string) {
  return `${patientId}#${specialistUserId}`;
}

export const DEMO_CHAT_THREADS: ChatThread[] = [
  {
    id: buildThreadId('MED-ELR-24018', 'user-nurse'),
    patientId: 'MED-ELR-24018',
    patientName: 'Sofia Marchetti',
    specialistUserId: 'user-nurse',
    specialistName: 'Elena Costa',
    specialistRole: 'nurse',
    hospitalId: 'ELR',
    subject: 'How are you feeling today?',
    preview: "Glad to hear it. If anything worsens before Saturday, please don't hesitate to call us.",
    lastMessageAt: '2026-06-24T12:00:00.000Z',
    unreadForPatient: false,
    unreadForSpecialist: false,
    urgent: false,
  },
  {
    id: buildThreadId('MED-ELR-24018', 'user-doctor'),
    patientId: 'MED-ELR-24018',
    patientName: 'Sofia Marchetti',
    specialistUserId: 'user-doctor',
    specialistName: 'Dr. Priya Sharma',
    specialistRole: 'doctor',
    hospitalId: 'ELR',
    subject: 'Question about my GTT appointment',
    preview: 'Hi, I wanted to ask when I should schedule the glucose tolerance test…',
    lastMessageAt: '2026-06-25T08:15:00.000Z',
    unreadForPatient: false,
    unreadForSpecialist: true,
    urgent: false,
  },
  {
    id: buildThreadId('MED-ELR-24012', 'user-nurse'),
    patientId: 'MED-ELR-24012',
    patientName: 'Ana Rodrigues',
    specialistUserId: 'user-nurse',
    specialistName: 'Elena Costa',
    specialistRole: 'nurse',
    hospitalId: 'ELR',
    subject: 'Missed visit follow-up',
    preview: "Hi Ana, we noticed you missed your appointment on June 14th…",
    lastMessageAt: '2026-06-22T14:00:00.000Z',
    unreadForPatient: true,
    unreadForSpecialist: false,
    urgent: true,
  },
];

export const DEMO_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'chat-msg-1',
    threadId: buildThreadId('MED-ELR-24018', 'user-nurse'),
    patientId: 'MED-ELR-24018',
    senderUserId: 'user-nurse',
    senderName: 'Elena Costa',
    senderRole: 'nurse',
    text: "Hi Sofia, just checking in. I saw you logged fatigue and mild dizziness earlier this week. Make sure you're resting between tasks and drinking enough water.",
    createdAt: '2026-06-24T10:30:00.000Z',
  },
  {
    id: 'chat-msg-2',
    threadId: buildThreadId('MED-ELR-24018', 'user-nurse'),
    patientId: 'MED-ELR-24018',
    senderUserId: 'user-mother-elr',
    senderName: 'Sofia Marchetti',
    senderRole: 'mother',
    text: "Thank you Elena. I've been resting more and drinking more water. The dizziness has been a bit better today.",
    createdAt: '2026-06-24T11:45:00.000Z',
  },
  {
    id: 'chat-msg-3',
    threadId: buildThreadId('MED-ELR-24018', 'user-nurse'),
    patientId: 'MED-ELR-24018',
    senderUserId: 'user-nurse',
    senderName: 'Elena Costa',
    senderRole: 'nurse',
    text: "Glad to hear it. If anything worsens before Saturday, please don't hesitate to call us. Take care!",
    createdAt: '2026-06-24T12:00:00.000Z',
  },
  {
    id: 'chat-msg-4',
    threadId: buildThreadId('MED-ELR-24018', 'user-doctor'),
    patientId: 'MED-ELR-24018',
    senderUserId: 'user-mother-elr',
    senderName: 'Sofia Marchetti',
    senderRole: 'mother',
    text: 'Hi, I wanted to ask when I should schedule the glucose tolerance test. My app shows it is due before July 15th.',
    createdAt: '2026-06-25T08:15:00.000Z',
  },
  {
    id: 'chat-msg-5',
    threadId: buildThreadId('MED-ELR-24012', 'user-nurse'),
    patientId: 'MED-ELR-24012',
    senderUserId: 'user-nurse',
    senderName: 'Elena Costa',
    senderRole: 'nurse',
    text: "Hi Ana, we noticed you missed your appointment on June 14th. Please reach out so we can reschedule.",
    createdAt: '2026-06-22T14:00:00.000Z',
    urgent: true,
  },
];
