export const PREGNANCY_FACTS = [
  // Baby in the womb — development & wonder
  'A baby\'s heart begins beating around 5–6 weeks — one of the first signs of the amazing journey ahead.',
  'By week 10, all of a baby\'s major organs have begun to form — your body is doing something extraordinary.',
  'Babies can hear sounds from outside the womb from about 18 weeks, and often recognize familiar voices after birth.',
  'Baby kicks and movements often become noticeable between 16 and 22 weeks — a special milestone many parents treasure.',
  'The amniotic fluid gently cushions your baby, keeps them warm, and helps their lungs develop.',
  'The placenta lovingly supplies oxygen and nutrients to your growing baby throughout pregnancy.',
  'A full-term pregnancy is about 40 weeks — each week brings new growth and new moments to look forward to.',
  'Most babies are born with blue-gray eyes; their permanent color often develops beautifully over the first year.',
  'The uterus expands from about the size of a pear to roughly that of a watermelon — your body adapts with strength.',
  'Babies practice swallowing amniotic fluid in the womb, gently preparing their digestive system for life outside.',
  'Babies store iron in the last weeks of pregnancy to give them a healthy start after birth.',
  'Hiccups in the womb are completely normal — many parents enjoy feeling those sweet rhythmic little bumps.',
  'A baby\'s brain develops rapidly in the third trimester — nourishment and rest help support this incredible growth.',
  'Talking and reading aloud to your bump is a lovely way to bond — babies often recognize familiar voices after birth.',
  'Fingerprints form on a baby\'s tiny hands around 10–16 weeks — already uniquely theirs.',
  'Babies begin making facial expressions in the womb and may even practice smiling before birth.',
  'By the third trimester, your baby can open and close their eyes and respond to light filtering through.',
  'Your baby\'s taste buds develop early — the flavors you enjoy may become familiar comforts after birth.',
  'Lanugo, the soft fine hair covering a baby in the womb, helps protect their skin until birth.',
  'Your baby\'s bones begin as soft cartilage and gradually strengthen — calcium-rich foods support this process.',
  'Tiny fingernails and toenails start forming around the end of the first trimester.',
  'Your baby\'s heartbeat is often twice as fast as yours — a lively rhythm of new life.',
  'Twins can share a special bond from the very beginning — double the wonder in one journey.',
  'Your baby spends much of the third trimester gaining weight and building strength for their grand entrance.',
  'Babies yawn, stretch, and suck their thumb in the womb — practicing skills they will use on day one.',
  'The sound of your heartbeat is one of the first rhythms your baby knows — a constant, comforting presence.',
  'Your baby\'s lungs mature throughout pregnancy, preparing for that very first breath of air.',
  'Every baby grows at their own pace — your care team celebrates your unique timeline with you.',
  'Ultrasound moments offer glimpses of your little one — tiny feet, waving hands, and peaceful rest.',
  'Your voice, your touch on your belly, and your calm presence are already part of your baby\'s world.',
  'By full term, your baby recognizes the rhythm of your daily life — your walks, meals, and rest.',
  'The bond between you and your baby begins long before birth — you are already their home.',
  'Your baby\'s eyelashes and eyebrows form in the second trimester — little details that make them uniquely them.',
  'In the womb, your baby cycles between active periods and peaceful sleep, just like they will after birth.',
  'Your growing belly is a visible reminder of the life you are nurturing — a journey worth honoring.',

  // What to eat — nourishing foods & gentle nutrition
  'Colorful fruits and berries bring natural sweetness plus vitamin C — try oranges, strawberries, or mango.',
  'Leafy greens like spinach and kale offer folate and iron — lovely in salads, soups, or smoothies.',
  'Whole grains such as oats, brown rice, and whole-wheat bread provide steady energy throughout the day.',
  'Greek yogurt and cottage cheese are excellent sources of protein and calcium for you and your baby.',
  'Eggs are a versatile source of protein and choline — scrambled, boiled, or in a nourishing omelette.',
  'Lentils, chickpeas, and beans add plant-based protein and fiber — perfect in curries, stews, and salads.',
  'Salmon and sardines offer omega-3 fats that support brain development — enjoy well-cooked portions as part of a balanced diet.',
  'Avocado brings healthy fats and creaminess — lovely on toast, in salads, or blended into smoothies.',
  'Sweet potatoes are rich in vitamin A and fiber — comforting baked, mashed, or roasted.',
  'Bananas offer potassium and gentle energy — a handy snack any time of day.',
  'Almonds, walnuts, and seeds add crunch, healthy fats, and protein to snacks and meals.',
  'Fortified plant milks can be a wonderful calcium source alongside dairy if that suits your diet.',
  'Broccoli, peppers, and carrots pack vitamins and minerals — roast them for an easy, colorful side dish.',
  'Peanut butter on whole-grain toast is a satisfying snack with protein and healthy fats.',
  'Hummus with vegetable sticks makes a fresh, protein-rich snack between meals.',
  'Small, frequent meals can feel gentler on your stomach — especially helpful in the first trimester.',
  'Ginger tea or a ginger biscuit is a soothing traditional comfort for morning queasiness.',
  'A warm bowl of oatmeal with fruit and nuts is a nourishing way to start the day.',
  'Hydrating foods like watermelon, cucumber, and citrus fruits count toward your daily fluid intake.',
  'Prenatal vitamins with folic acid and iron complement a balanced diet — your clinician can suggest one you like.',
  'Iron-rich foods like lean red meat, spinach, and fortified cereals support your expanded blood volume.',
  'Calcium from milk, cheese, yogurt, or fortified alternatives helps build your baby\'s bones and teeth.',
  'Protein at each meal — eggs, fish, tofu, chicken, or beans — supports steady growth for your baby.',
  'A handful of dried apricots or dates offers iron and natural sweetness in a portable snack.',
  'Quinoa and buckwheat are protein-rich grains that work beautifully in warm bowls and salads.',
  'Mashed avocado on whole-grain crackers is a simple, satisfying mini-meal.',
  'A fruit smoothie with yogurt, banana, and berries is an easy way to pack in nutrients.',
  'Vegetable soups and broths are warm, hydrating, and gentle — especially when appetite varies.',
  'Dark chocolate in moderation can be a joyful treat — it also contains iron and magnesium.',
  'Cooked mushrooms add umami flavor and B vitamins to pastas, stir-fries, and omelettes.',
  'Pasta with tomato sauce and grated cheese is a comforting classic that provides energy and calcium.',
  'Ripe mango, papaya, and pineapple bring tropical vitamins and natural energy on sunny days.',
  'A cheese and whole-grain sandwich with lettuce and tomato is a balanced, satisfying lunch.',
  'Creamy soups with lentils or split peas offer warmth, protein, and fiber in one bowl.',
  'Sipping water regularly throughout the day keeps you refreshed and supports amniotic fluid.',

  // Newborn babies — sweet first moments
  'Newborns typically sleep 14–17 hours a day in cozy stretches — rest is their first great skill.',
  'Skin-to-skin contact after birth helps your baby feel secure, warm, and close to your heartbeat.',
  'Breast milk naturally adapts to your baby\'s needs, even changing composition during a single feed.',
  'A newborn\'s grasp reflex is strong — those tiny fingers curling around yours is a moment many parents never forget.',
  'Babies are born with a natural rooting reflex, turning toward touch near their cheek when hungry.',
  'Newborns can see best at about 8–12 inches — the perfect distance to gaze into your eyes while feeding.',
  'Your baby\'s first cry fills their lungs with air — a powerful welcome to the world.',
  'Newborn sneezes are normal and help clear their tiny nasal passages — not necessarily a sign of a cold.',
  'A baby\'s head may look slightly rounded or molded after birth and settles beautifully in the days that follow.',
  'Newborns love the sound of voices — talking, singing, and humming are wonderful ways to connect.',
  'Baby smiles begin as reflexes and become social smiles around 6–8 weeks — each one feels like sunshine.',
  'Newborns often curl up in the fetal position — a cozy reminder of the months they spent with you.',
  'Your baby\'s sense of smell is keen from birth — they recognize your scent and find it deeply comforting.',
  'Soft lullabies and gentle rocking can soothe a newborn — you are already their favorite comfort.',
  'Newborn hiccups are harmless and common — many babies hiccup frequently and it rarely bothers them.',
  'A warm bath can be a calming ritual for you and your baby as you settle into your new rhythm together.',
  'Newborns grow quickly in the first weeks — those tiny outfits will be cherished memories before you know it.',
  'Tummy time, even for short moments while you are nearby, helps build your baby\'s neck and shoulder strength.',
  'Your baby\'s first bath at home can become a sweet weekly tradition — warm water, soft towels, and your gentle hands.',
  'Reading picture books to your newborn introduces rhythm and language — they love hearing your voice.',
  'Newborns often have quiet alert periods each day — perfect windows for eye contact and connection.',
  'A newborn\'s tummy is small — frequent, gentle feeds are normal and expected in the early weeks.',
  'Swaddling in a light blanket can help some newborns feel snug and secure, like the womb they know.',
  'Your baby\'s first laugh, when it comes, will feel like the brightest sound in the room.',
  'Newborn toes and fingers are perfect for gentle counting games — a sweet ritual anytime.',

  // Supportive wellness — encouragement & self-care
  'The second trimester is often called the "golden period" — many people feel more energy and appetite return.',
  'Every pregnancy is different — your story is yours, and your care team is there to walk it with you.',
  'Rest when your body asks for it — growing a baby is meaningful work, and rest is part of the care.',
  'A supportive pillow between your knees can make side sleeping more comfortable as your bump grows.',
  'Gentle walks outdoors can lift your mood, ease tension, and give you fresh air and sunshine.',
  'Prenatal yoga and stretching can ease back tension and help you feel centered and strong.',
  'Swimming and water aerobics feel weightless and refreshing — especially lovely in the later months.',
  'Pelvic floor exercises support your body during pregnancy and help with recovery afterward.',
  'Deep, slow breathing for a few minutes can bring calm anytime — a gift you can share with your baby too.',
  'Keeping a list of happy questions for your next visit helps you make the most of time with your care team.',
  'Your partner, family, or friends can share in appointments and learn how to support you along the way.',
  'Writing down your birth preferences helps your team understand your hopes — flexibility is part of the plan too.',
  'Prepare a few freezer meals before birth — a thoughtful gift to your future self in those first cozy weeks.',
  'Pack a hospital bag with snacks, comfy clothes, and something special for baby — a little nest of readiness.',
  'Postpartum is a time for gentle recovery — your body continues its amazing work of healing and adapting.',
  'Accepting help with meals, laundry, or errands lets you focus on rest and bonding with your new baby.',
  'Breastfeeding support groups and lactation consultants are warm, knowledgeable allies — many hospitals can connect you.',
  'Partners who learn comfort techniques and share night feeds make the early weeks a shared adventure.',
  'Building a support network early — friends, family, or community groups — means more hands and hearts around you.',
  'Braxton Hicks contractions are gentle practice tightenings — your body preparing with quiet rehearsals.',
  'Morning sickness often eases as the weeks go by — bland comforts like toast, crackers, and rice can help in the meantime.',
  'Your care team increases visits in later pregnancy because they enjoy checking in on you and your growing baby.',
  'Feeling your baby move is a reassuring connection — many parents describe it as the best part of the day.',
  'Pregnancy glow is real for many — increased blood flow can bring a natural radiance to your skin.',
  'You are doing something remarkable — be as kind to yourself as you are to the life you are growing.',
] as const;

/** Newborn & first-year facts (lines 76–101 in the array above). */
export const NEWBORN_FACTS = PREGNANCY_FACTS.slice(75, 101);

/** Pregnancy-only facts for loader tips during gestation. */
export const GESTATION_FACTS = [
  ...PREGNANCY_FACTS.slice(0, 75),
  ...PREGNANCY_FACTS.slice(101),
];

export function pickRandomPregnancyFact(careStage?: "pregnant" | "postpartum"): string {
  const pool = careStage === "postpartum" ? NEWBORN_FACTS : GESTATION_FACTS;
  const index = Math.floor(Math.random() * pool.length);
  return pool[index];
}
